### ISSUE TITLE
Лишние переменные

### ISSUE THREAD

**Issue by ilya-grigoriev** [LAffey26/race#19]
```python
WHITE = race.config.WHITE
WIDTH = race.config.WIDTH 
branch = race.config.branch 
```
- Подобные переменные бессмысленны и не несут никакой пользы.

**Comment by LAffey26** [comment]
чтобы в каждый раз не писать race.config.WHITE или WIDHT

**Comment by ilya-grigoriev** [comment]
Так ты эти переменные из модуля импортируй, а не сам модуль.
