### ISSUE TITLE
Гибкость настройки проекта

### ISSUE THREAD

**Issue by ilya-grigoriev** [LAffey26/race#9]
Хотелось бы иметь удобный способ изменять ширину и высоту экрана либо сделать адапативную настройку.

**Comment by LAffey26** [comment]
Если я даже сделаю настройку разрешения через pillow, координаты границ и объектов будут иметь те же значения

**Comment by ilya-grigoriev** [comment]
Так настройка ширины и высоты изображения будет происходить через сам Pillow.

**Comment by LAffey26** [comment]
не знаю как это реализовать
